one small bug about CopyTable when rowkey is null
Summary:
one small bug about CopyTable when rowkey is null
rowkey为空时，currentValue为maxValue(), Preconditions.checkArgument(currentValue >= startValue && currentValue <= endValue);报错如下
15/08/31 20:01:10 INFO mapreduce.Job: Task Id : attempt_1440669973703_5763_m_000000_2, Status : FAILED
Error: java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:72)
	at org.apache.hadoop.hbase.mapreduce.ProgressEstimator.getProgress(ProgressEstimator.java:51)
	at org.apache.hadoop.hbase.mapreduce.TableRecordReaderImpl.getProgress(TableRecordReaderImpl.java:292)
	at org.apache.hadoop.hbase.mapreduce.TableRecordReader.getProgress(TableRecordReader.java:147)
	at org.apache.hadoop.mapred.MapTask$NewTrackingRecordReader.getProgress(MapTask.java:544)
	at org.apache.hadoop.mapred.MapTask$NewTrackingRecordReader.nextKeyValue(MapTask.java:566)
	at org.apache.hadoop.mapreduce.task.MapContextImpl.nextKeyValue(MapContextImpl.java:80)
	at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.nextKeyValue(WrappedMapper.java:91)
	at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:160)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:791)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:342)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:163)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:396)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1854)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)

Test Plan: N/A

Reviewers: heliangliang, chengqiming, liushaohui, fenghonghua, cuijianwei

Reviewed By: cuijianwei

Differential Revision: https://phabricator.d.xiaomi.net/D20153